services:
  - type: web
    name: arto-chatbot
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -p $PORT"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: arto-chatbot-db
          property: connectionString
    autoDeploy: true

  - type: postgres
    name: arto-chatbot-db
    databaseName: arto_chatbot_production
    region: oregon
    plan: free